### ISSUE TITLE
Identifier "default" as connection name is mandatory?

### ISSUE THREAD

**Issue by Felsfungus** [mogilvie/EncryptBundle#38]
Hey,

i installed version v2.0.1 of EncryptBundle and i'm getting the following error message:

```
!!    The Doctrine connection "default" referenced in service "SpecShaper\Encrypt  
!!    Bundle\Subscribers\DoctrineEncryptSubscriberInterface" does not exist. Avai  
!!    lable connections names: ..., ..., ...
```

I do not have a connection named "default" for reasons. Can i configure the bundle in any way not to use the connection named "default"? In my doctrine.yaml i configured the default connection this way:

```yaml
doctrine:
    dbal:
        default_connection: myconnection
```
When configuring a connection named "default" the error is gone, but i would like not to have a connection named "default".

Thank you for your work :-)

**Comment by Felsfungus** [comment]
After some debugging i found out, that the default connection is needed for installation, but we can override the connection by service configuration:

```
    \SpecShaper\EncryptBundle\Subscribers\DoctrineEncryptSubscriber:
        class: '%spec_shaper_encrypt.subscriber_class%'
        arguments:
            $annotationArray: '%spec_shaper_encrypt.annotation_classes%'
            $isDisabled: '%spec_shaper_encrypt.is_disabled%'
        tags:
            - { name: doctrine.event_subscriber, connection: api }
```

Is that the way i should go or is there a better way?
