### ISSUE TITLE
Missing service with symfony 7.1.8

### ISSUE THREAD

**Issue by tgiraudeau-prolaser** [mogilvie/EncryptBundle#61]
I've got an error when i tried to clear cache with symfony 7.1.8 :

![image](https://github.com/user-attachments/assets/bc49b7db-a1fd-4678-9f5a-8624cb13de16)

**Comment by shochdoerfer** [comment]
Not ideal, but I could solve this by defining the following service in my services.yaml file:
```YAML
services:
    # needed by specshaper/encrypt-bundle
    Doctrine\Common\Annotations\Reader:
        class: Doctrine\Common\Annotations\AnnotationReader
```
